name: HACK.<strong>CODE</strong>.VOID.<strong>MAKE</strong>
blurb: A <strong>Ballarat</strong> Hackerspace
copyright: Ballarat Hackerspace
markdown: redcarpet
pygments: true
siteurl: http://bhack.in
emailaddress: hello@bhack.in
communityurl: https://plus.google.com/communities/106879016585907671427
