name: bhack.in
blurb: The Ballarat Hackerspace
copyright: Ballarat Hackerspace
markdown: redcarpet
pygments: true
siteurl: http://bhack.in/
emailaddress: hello@bhack.in
communityurl: https://plus.google.com/communities/106879016585907671427
