name: bhack.in
blurb: The Ballarat Hackerspace
copyright: Ballarat Hackerspace
markdown: redcarpet
pygments: true
siteurl: http://bhack.in/
emailaddress: hello@bhack.in
communityurl: https://plus.google.com/communities/106879016585907671427

navlinks:
  - text: About Us
    url: /hello/
  - text: Projects
    url: /projects/
  - text: Contact Us
    url: /contact/

links:
  - text: <i class="fa fa-google-plus"></i> Community
    url: https://plus.google.com/communities/106879016585907671427
  - text: <i class='fa fa-github'></i> GitHub
    url: https://github.com/ballarat-hackerspace/
  - text: <i class="fa fa-asterisk"></i> Wiki
    url: https://github.com/ballarat-hackerspace/ballarat-hackerspace.github.io/wiki
